# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'WasteReduction' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WasteReduction
  pod 'DynamicButton', '~> 6.2.1'
  pod 'Parchment'
  pod 'Hero'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'AIFlatSwitch'
  pod 'NotificationBannerSwift', '~> 3.0.0'
  pod 'SwipeCellKit'
  pod 'JGProgressHUD'
  pod 'NVActivityIndicatorView'
end
